#!/usr/bin/env python
#
# -*- encoding: utf-8 -*-
#
# generated by wxGlade HG on Wed Jul 18 14:54:33 2012
#

# This is the main entry point of the editor.

import wx
from pvsmainframe import PVSMainFrame
import config

log = config.getLogger(__name__)

class PVSEditorApp(wx.App):
    
    def OnInit(self):
        wx.InitAllImageHandlers()
        self.mainFrame = PVSMainFrame(None, wx.ID_ANY, "")
        self.SetTopWindow(self.mainFrame)
        self.mainFrame.Show()
        log.info("Editor initialized...") 
        return 1

# end of class PVSEditorApp

if __name__ == "__main__":
    config.editor = PVSEditorApp(0)
    log.info("Entering MainLoop...") 
    config.editor.MainLoop()
