#!/usr/bin/env python
#
# -*- encoding: utf-8 -*-
#
# generated by wxGlade HG on Wed Jul 18 14:54:33 2012
#

# This is the main entry point of the editor.

import wx, os.path, sys
import util
import logging
import constants
import platform
import time
from ui.images import getIDELogo
from ui.frame import MainFrame
from ui.plugin import PluginManager
from ui.plg.ft import FilesTreePlugin
from ui.plg.pt import ProofTreePlugin
from ui.plg.console import ConsolePlugin
from config import PLUGIN_DEFINITIONS

log = util.getLogger(__name__)

class PVSEditorApp(wx.App):
    """The main class that starts the application and shows the main frame"""
    
    def OnInit(self):
        #wx.InitAllImageHandlers()
        
        # Splash Screen:
        #splash = wx.SplashScreen(getIDELogo(), wx.SPLASH_CENTRE_ON_SCREEN|wx.SPLASH_TIMEOUT, 1000, None, style=wx.SIMPLE_BORDER|wx.STAY_ON_TOP)
        #time.sleep(1)
        
        #Initiate Main Frame:
        mainFrame = MainFrame(None, wx.ID_ANY, "")
        self.SetTopWindow(mainFrame)
        mainFrame.Show()
        log.info("Main Frame initialized...") 
        pm = PluginManager()
        pm.initializePlugins(PLUGIN_DEFINITIONS)
        operatingSystem = platform.system()
        if operatingSystem == "Windows":
            mainFrame.showDialogBox("PVS does not run on Windows", constants.WARNING)
        mainFrame.loadContext()
        return 1

# end of class PVSEditorApp

def processArguments(args):
    log.info("Command Line Arguments: %s", args)
    del args[0]
    for arg in args:
        if arg.startswith(constants.INPUT_LOGGER):
            logLevel = arg[len(constants.INPUT_LOGGER):]
            if logLevel == constants.LOG_LEVEL_DEBUG:
                constants.LOGGER_LEVEL = logging.DEBUG
            elif logLevel == constants.LOG_LEVEL_DEBUG:
                constants.LOGGER_LEVEL = logging.FATAL
            

if __name__ == "__main__":
    utilDirectory = os.path.dirname(util.__file__)
    try:
        from wx.lib.pubsub import pub    
    except ImportError:
        print "Could not import the new PubSub (version 3)."
        print "Please go to http://pubsub.sourceforge.net/ and install the latest PubSub"
        sys.exit(1)
    constants.APPLICATION_FOLDER = os.path.abspath(os.path.join(utilDirectory, os.path.pardir))
    constants.IMAGE_FOLDER_PATH = os.path.join(constants.APPLICATION_FOLDER, constants.IMAGE_FOLDER_NAME)
    log.debug("Application Folder is %s", constants.APPLICATION_FOLDER)
    processArguments(list(sys.argv))

    application = PVSEditorApp(0)
    log.info("Entering MainLoop...") 
    application.MainLoop()
