#!/usr/bin/env python
#
# -*- encoding: utf-8 -*-
#
# generated by wxGlade HG on Wed Jul 18 14:54:33 2012
#

# This is the main entry point of the editor.

import wx, os.path, sys
import util
import constants
import platform
import time
import config
import logging
import logging.config
from ui.images import getIDELogo
from ui.frame import MainFrame
from ui.plugin import PluginManager
from ui.plg.ft import FilesTreePlugin
from ui.plg.pt import ProofTreePlugin
from ui.plg.console import ConsolePlugin
from config import PLUGIN_DEFINITIONS
from wx.lib.pubsub import setupkwargs, pub 

class PVSEditorApp(wx.App):
    """The main class that starts the application and shows the main frame"""
    
    def OnInit(self):
        #wx.InitAllImageHandlers()
        
        # Splash Screen:
        #splash = wx.SplashScreen(getIDELogo(), wx.SPLASH_CENTRE_ON_SCREEN|wx.SPLASH_TIMEOUT, 1000, None, style=wx.SIMPLE_BORDER|wx.STAY_ON_TOP)
        #time.sleep(1)
        
        #Initiate Main Frame:
        mainFrame = MainFrame(None, wx.ID_ANY, "")
        self.SetTopWindow(mainFrame)
        mainFrame.Show()
        logging.info("Main Frame initialized...") 
        pm = PluginManager()
        pm.initializePlugins(PLUGIN_DEFINITIONS)
        operatingSystem = platform.system()
        if operatingSystem == "Windows":
            mainFrame.showDialogBox("PVS does not run on Windows", constants.WARNING)
        mainFrame.loadContext()
        return 1

# end of class PVSEditorApp

def processArguments(args):
    logging.info("Command Line Arguments: %s", args)
    del args[0]
    for arg in args:
        if arg.startswith(constants.INPUT_LOGGER):
            logLevel = arg[len(constants.INPUT_LOGGER):]
            if logLevel == constants.LOG_LEVEL_DEBUG:
                constants.LOGGER_LEVEL = logging.DEBUG
            elif logLevel == constants.LOG_LEVEL_DEBUG:
                constants.LOGGER_LEVEL = logging.FATAL
            
def configLogger():
    """Return a logger for the given name"""
    logConfigFile = os.path.join(constants.APPLICATION_FOLDER, "src/logging.cnfg")
    if os.path.exists(logConfigFile):
        logging.config.fileConfig(logConfigFile)
    else:
        print "Could not find the config file for logging. Using default settings..."
        hdlr = logging.StreamHandler(sys.stdout)
        formatter = logging.Formatter("[%(module)s %(funcName)s] %(levelname)s - %(message)s")
        hdlr.setFormatter(formatter)
        logging.addHandler(hdlr) 
        logging.setLevel(logging.DEBUG)

if __name__ == "__main__":
    #logging.debug("PubSub version is %s", pub.PUBSUB_VERSION)
    assert pub.PUBSUB_VERSION == 3
    utilDirectory = os.path.dirname(util.__file__)
    constants.APPLICATION_FOLDER = os.path.abspath(os.path.join(utilDirectory, os.path.pardir))
    constants.IMAGE_FOLDER_PATH = os.path.join(constants.APPLICATION_FOLDER, constants.IMAGE_FOLDER_NAME)
    configLogger()
    logging.debug("Application Folder is %s", constants.APPLICATION_FOLDER)
    processArguments(list(sys.argv))

    application = PVSEditorApp(0)
    logging.info("Entering MainLoop...") 
    application.MainLoop()
