CC=gcc
CFLAGS=-I.

%.o: %.c
	$(CC) -c -o $@ $< $(CFLAGS)
all:
	g++ -fPIC -Wall -c fmu.cpp
	g++ -fPIC -Wall -c skeleton.cpp
	g++ -shared -o {{name}}.so skeleton.o fmu.o -lwebsockets -lssl -lcrypto
	mv {{name}}.so binaries/linux64/
	zip -r {{name}}.fmu modelDescription.xml binaries/ resources/

run:
	./fmuCheck.linux64 -h 1E-01 {{name}}.fmu
run1:
	./fmuCheck.linux64 -h 1E-02 {{name}}.fmu

clean:
	rm -rf {{name}}.fmu {{name}}.o fmu.o
