(in-package 'PVS)

(DEFUN |print_0| ()
  #'(LAMBDA (|LAMVAR#0|)
      (LET ((|a| (PROJECT 1 |LAMVAR#0|)) (|s| (PROJECT 2 |LAMVAR#0|)))
        (DECLARE (TYPE STRING |s|))
        T)))
(DEFUN |_print_0| (|a| |s|) (DECLARE (TYPE STRING |s|)) T)
(DEFUN |print!_0| (|a| |s|) (DECLARE (TYPE STRING |s|)) T)
(DEFUN |pvsprint_0| ()
  #'(LAMBDA (|LAMVAR#0|)
      (LET ((|a| (PROJECT 1 |LAMVAR#0|)) (|s| (PROJECT 2 |LAMVAR#0|)))
        (DECLARE (TYPE STRING |s|))
        T)))
(DEFUN |_pvsprint_0| (|a| |s|) (DECLARE (TYPE STRING |s|)) T)
(DEFUN |pvsprint!_0| (|a| |s|) (DECLARE (TYPE STRING |s|)) T)
(DEFUN |printa_0| ()
  #'(LAMBDA (|a|) (|_print_0| |a| (THE STRING " ~a"))))
(DEFUN |_printa_0| (|a|) (|_print_0| |a| (THE STRING " ~a")))
(DEFUN |printa!_0| (|a|) (|print!_0| |a| (THE STRING " ~a")))
(DEFUN |write_0| () #'(LAMBDA (|a|) T))
(DEFUN |_write_0| (|a|) T)
(DEFUN |write!_0| (|a|) T)
(DEFUN |printset_0| ()
  #'(LAMBDA (|a|) (THE BOOLEAN (FUNCALL '|undefined61|))))
(DEFUN |_printset_0| (|a|) (THE BOOLEAN (FUNCALL '|undefined59|)))
(DEFUN |printset!_0| (|a|) (THE BOOLEAN (FUNCALL '|undefined60|)))