/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 *
 *   Created: Fri Nov  1 17:14:30 1996
 */
#ifndef _polyhedron_h_
#define _polyhedron_h_
#if __STDC__

extern Polyhedron *AddConstraints ( int *Con2, unsigned NbCon2,
                                    Polyhedron *Pol1, unsigned NbMaxRays );
extern Polyhedron *AddPolyToDomain ( Polyhedron *p3, Polyhedron *p3beg );
extern Polyhedron *Constraints2Polyhedron ( Matrix *Constraints, unsigned
                                            NbMaxRays );
extern Polyhedron *DomainAddConstraints ( Polyhedron *Pol1, Matrix *Mat2,
                                          unsigned NbMaxRays );
extern Polyhedron *DomainAddRays ( Polyhedron *Pol1, Matrix *Mat2,
                                   unsigned NbMaxRays );
extern Polyhedron *DomainConvex ( Polyhedron *Pol1, int NbMaxRays );
extern Polyhedron *DomainDifference ( Polyhedron *Pol1, Polyhedron *Pol2,
                                      unsigned NbMaxRays );
extern Polyhedron *DomainImage ( Polyhedron *Pol1, Matrix *Func, unsigned
                                 NbMaxRays );
extern Polyhedron *DomainIntersection ( Polyhedron *Pol1, Polyhedron
                                        *Pol2, unsigned NbMaxRays );
extern Polyhedron *DomainPreimage ( Polyhedron *Pol1, Matrix *Func,
                                    unsigned NbMaxRays );
extern Polyhedron *DomainSimplify ( Polyhedron *Pol1, Polyhedron *Pol2,
                                    unsigned NbMaxRays );
extern Polyhedron *DomainUnion ( Polyhedron *Pol1, Polyhedron *Pol2,
                                 unsigned NbMaxRays );
extern Polyhedron *Domain_Copy ( Polyhedron *Pol );
extern void Domain_Free ( Polyhedron *Pol );
extern Polyhedron *Empty_Polyhedron ( unsigned Dimension );
extern int Gauss ( Matrix *Mat, int NbEq, int Dimension, int *temp );
extern Matrix *Polyhedron2Constraints ( Polyhedron *Pol );
extern Matrix *Polyhedron2Rays ( Polyhedron *Pol );
extern int PolyhedronIncludes ( Polyhedron *Pol1, Polyhedron *Pol2 );
extern Polyhedron *Polyhedron_Alloc ( unsigned Dimension, unsigned
                                      NbConstraints, unsigned NbRays );
extern Polyhedron *Polyhedron_Copy ( Polyhedron *Pol );
extern void Polyhedron_Free ( Polyhedron *Pol );
extern Polyhedron *Polyhedron_Image ( Polyhedron *Pol1, Matrix *Func,
                                      unsigned NbMaxRays );
extern Polyhedron *Polyhedron_Preimage ( Polyhedron *Pol1, Matrix *Func,
                                         unsigned NbMaxRays );
extern void Polyhedron_Print ( FILE *Dst, char *Format, Polyhedron *Pol );
extern Polyhedron *Rays2Polyhedron ( Matrix *Ray, unsigned NbMaxRays );
extern Polyhedron *SubConstraint ( int *Con2, Polyhedron *Pol1, unsigned
                                   NbMaxRays, int Pass );
extern Matrix *TransformSat ( Matrix *Mat, Matrix *Ray, Matrix *Sat );
extern Polyhedron *Universe_Polyhedron ( unsigned Dimension );

#else /* __STDC__ */

extern Polyhedron *AddConstraints (/* int *Con2, unsigned NbCon2,
                                    Polyhedron *Pol1, unsigned NbMaxRays */);
extern Polyhedron *AddPolyToDomain (/* Polyhedron *p3, Polyhedron *p3beg */);
extern Polyhedron *Constraints2Polyhedron (/* Matrix *Constraints,
                                            unsigned NbMaxRays */);
extern Polyhedron *DomainAddConstraints (/* Polyhedron *Pol1, Matrix
                                          *Mat2, unsigned NbMaxRays */);
extern Polyhedron *DomainAddRays (/* Polyhedron *Pol1, Matrix *Mat2,
                                   unsigned NbMaxRays */);
extern Polyhedron *DomainConvex (/* Polyhedron *Pol1, int NbMaxRays */);
extern Polyhedron *DomainDifference (/* Polyhedron *Pol1, Polyhedron
                                      *Pol2, unsigned NbMaxRays */);
extern Polyhedron *DomainImage (/* Polyhedron *Pol1, Matrix *Func,
                                 unsigned NbMaxRays */);
extern Polyhedron *DomainIntersection (/* Polyhedron *Pol1, Polyhedron
                                        *Pol2, unsigned NbMaxRays */);
extern Polyhedron *DomainPreimage (/* Polyhedron *Pol1, Matrix *Func,
                                    unsigned NbMaxRays */);
extern Polyhedron *DomainSimplify (/* Polyhedron *Pol1, Polyhedron *Pol2,
                                    unsigned NbMaxRays */);
extern Polyhedron *DomainUnion (/* Polyhedron *Pol1, Polyhedron *Pol2,
                                 unsigned NbMaxRays */);
extern Polyhedron *Domain_Copy (/* Polyhedron *Pol */);
extern void Domain_Free (/* Polyhedron *Pol */);
extern Polyhedron *Empty_Polyhedron (/* unsigned Dimension */);
extern int Gauss (/* Matrix *Mat, int NbEq, int Dimension, int *temp */);
extern Matrix *Polyhedron2Constraints (/* Polyhedron *Pol */);
extern Matrix *Polyhedron2Rays (/* Polyhedron *Pol */);
extern int PolyhedronIncludes (/* Polyhedron *Pol1, Polyhedron *Pol2 */);
extern Polyhedron *Polyhedron_Alloc (/* unsigned Dimension, unsigned
                                      NbConstraints, unsigned NbRays */);
extern Polyhedron *Polyhedron_Copy (/* Polyhedron *Pol */);
extern void Polyhedron_Free (/* Polyhedron *Pol */);
extern Polyhedron *Polyhedron_Image (/* Polyhedron *Pol1, Matrix *Func,
                                      unsigned NbMaxRays */);
extern Polyhedron *Polyhedron_Preimage (/* Polyhedron *Pol1, Matrix
                                         *Func, unsigned NbMaxRays */);
extern void Polyhedron_Print (/* FILE *Dst, char *Format, Polyhedron *Pol */);
extern Polyhedron *Rays2Polyhedron (/* Matrix *Ray, unsigned NbMaxRays */);
extern Polyhedron *SubConstraint (/* int *Con2, Polyhedron *Pol1,
                                   unsigned NbMaxRays, int Pass */);
extern Matrix *TransformSat (/* Matrix *Mat, Matrix *Ray, Matrix *Sat */);
extern Polyhedron *Universe_Polyhedron (/* unsigned Dimension */);

#endif /* __STDC__ */
#endif /* _polyhedron_h_ */
