/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 *
 *   Created: Fri Nov  1 17:16:07 1996
 */
#ifndef _vector_h_
#define _vector_h_
#if __STDC__

extern int Binomial ( int n, int p );
extern int CNP ( int a, int b );
extern int Factorial ( int n );
extern int First_Non_Zero ( int *p, unsigned length );
extern int Gcd ( int a, int b );
extern int Inner_Product ( int *p1, int *p2, unsigned length );
extern Matrix *Matrix_Alloc ( unsigned NbRows, unsigned NbColumns );
extern void Matrix_Free ( Matrix *Mat );
extern void Matrix_Print ( FILE * Dst, char *Format, Matrix *Mat );
extern void Matrix_Product ( Matrix *mat1, Matrix *mat2, Matrix *mat3 );
extern Matrix *Matrix_Read ( void );
extern void Matrix_Vector_Product ( Matrix *mat, int *p1, int *p2 );
extern void Vector_Add ( int *p1, int *p2, int *p3, unsigned length );
extern Vector *Vector_Alloc ( unsigned length );
extern void Vector_AntiScale ( int *p1, int *p2, int lambda, unsigned
                               length );
extern void Vector_Combine ( int *p1, int *p2, int *p3, int lambda, int
                             mu, unsigned length );
extern int Vector_Equal ( int *Vec1, int *Vec2, unsigned n );
extern void Vector_Free ( Vector *vec );
extern int Vector_Gcd ( int *p, int *q, unsigned length );
extern void Vector_Map ( int *p1, int *p2, int *p3, unsigned length, int
                         (*f)() );
extern void Vector_Matrix_Product ( int *p1, Matrix *mat, int *p2 );
extern int Vector_Max ( int *p, unsigned length );
extern int Vector_Min ( int *p, unsigned length );
extern void Vector_Normalize ( int *p, int *tmp, int length );
extern void Vector_Normalize_Positive ( int *p, int *tmp, int length, int
                                        pos );
extern void Vector_Or ( int *p1, int *p2, int *p3, unsigned length );
extern void Vector_Print ( FILE *Dst, char *Format, Vector *Vec );
extern Vector *Vector_Read ( void );
extern int Vector_Reduce ( int *p, unsigned length, int (*f)() );
extern void Vector_Scale ( int *p1, int *p2, int lambda, unsigned length );
extern void Vector_Set ( int *p, int n, unsigned length );
extern void Vector_Sort ( int *Vec, unsigned n );
extern void Vector_Sub ( int *p1, int *p2, int *p3, unsigned length );

#else /* __STDC__ */

extern int Binomial (/* int n, int p */);
extern int CNP (/* int a, int b */);
extern int Factorial (/* int n */);
extern int First_Non_Zero (/* int *p, unsigned length */);
extern int Gcd (/* int a, int b */);
extern int Inner_Product (/* int *p1, int *p2, unsigned length */);
extern Matrix *Matrix_Alloc (/* unsigned NbRows, unsigned NbColumns */);
extern void Matrix_Free (/* Matrix *Mat */);
extern void Matrix_Print (/* FILE * Dst, char *Format, Matrix *Mat */);
extern void Matrix_Product (/* Matrix *mat1, Matrix *mat2, Matrix *mat3 */);
extern Matrix *Matrix_Read (/* void */);
extern void Matrix_Vector_Product (/* Matrix *mat, int *p1, int *p2 */);
extern void Vector_Add (/* int *p1, int *p2, int *p3, unsigned length */);
extern Vector *Vector_Alloc (/* unsigned length */);
extern void Vector_AntiScale (/* int *p1, int *p2, int lambda, unsigned
                               length */);
extern void Vector_Combine (/* int *p1, int *p2, int *p3, int lambda, int
                             mu, unsigned length */);
extern int Vector_Equal (/* int *Vec1, int *Vec2, unsigned n */);
extern void Vector_Free (/* Vector *vec */);
extern int Vector_Gcd (/* int *p, int *q, unsigned length */);
extern void Vector_Map (/* int *p1, int *p2, int *p3, unsigned length,
                         int (*f)() */);
extern void Vector_Matrix_Product (/* int *p1, Matrix *mat, int *p2 */);
extern int Vector_Max (/* int *p, unsigned length */);
extern int Vector_Min (/* int *p, unsigned length */);
extern void Vector_Normalize (/* int *p, int *tmp, int length */);
extern void Vector_Normalize_Positive (/* int *p, int *tmp, int length,
                                        int pos */);
extern void Vector_Or (/* int *p1, int *p2, int *p3, unsigned length */);
extern void Vector_Print (/* FILE *Dst, char *Format, Vector *Vec */);
extern Vector *Vector_Read (/* void */);
extern int Vector_Reduce (/* int *p, unsigned length, int (*f)() */);
extern void Vector_Scale (/* int *p1, int *p2, int lambda, unsigned
                           length */);
extern void Vector_Set (/* int *p, int n, unsigned length */);
extern void Vector_Sort (/* int *Vec, unsigned n */);
extern void Vector_Sub (/* int *p1, int *p2, int *p3, unsigned length */);

#endif /* __STDC__ */
#endif /* _vector_h_ */
