\input texinfo   @c -*-texinfo-*-
@c %**start of header
@setfilename pvs-release-notes.info
@settitle PVS Release Notes
@setchapternewpage odd
@paragraphindent 0
@c %**end of header

@ifinfo
This file contains the release notes for PVS versions 3.0 - 3.3

Copyright 2002 SRI International
@end ifinfo

@c  This title page illustrates only one of the
@c  two methods of forming a title page.

@titlepage
@title PVS Release Notes
@author Sam Owre <owre@@csl.sri.com>
@author SRI International
@author December 15, 2005
@page
@end titlepage

@ifinfo
@node Top
@top PVS Release Notes
@end ifinfo

@c @node Introduction
@chapter Introduction

The PVS release notes are given here, for each version, going back to
version 3.0.

You can always download the latest version of PVS from@*
@uref{http://pvs.csl.sri.com/download.html}.

Note that the release notes are now written in texinfo, and are thus
available in Emacs info, HTML, Postscript, and PDF forms.  @code{M-x
pvs-release-notes} brings up the info files while in PVS.  The others
are available in the @code{doc/release-notes} subdirectory of the PVS
distribution.

@menu
* PVS 3.3 Release Notes::
* PVS 3.2 Release Notes::
* PVS 3.1 Release Notes::
* PVS 3.0 Release Notes::
@end menu

@include pvs3.3-release-notes.texi
@include pvs3.2-release-notes.texi
@include pvs3.1-release-notes.texi
@include pvs3.0-release-notes.texi

@iftex
@sp 1
@end iftex

@summarycontents
@contents
@bye

